services:
  backend:
    build:
      context: ./studybuddy
      dockerfile: Dockerfile
    container_name: studybuddy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./studybuddy:/app
    env_file:
      - ./studybuddy/.env
    depends_on:
      - db
    expose:  # Make the backend visible to Nginx
      - 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studybuddy-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: studybuddy-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studybuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: studybuddy-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
      - /var/www/html:/var/www/html
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: studybuddy-certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'

volumes:
  postgres_data:
