version: '3.8'

services:
  api:
    build:
      context: ./studybuddy       # Corrected path to the Dockerfile
    container_name: api
    restart: always
    expose:
      - 8000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend         # Path remains the same for the frontend
    container_name: frontend
    restart: always
    expose:
      - 80
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./frontend/build:/var/www/frontend
    depends_on:
      - api
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 5; done'"

networks:
  app-network:
    driver: bridge
