services:
  nginx:
    image: nginx:latest
    container_name: studybuddy-nginx
    ports:
      - "443:443" # HTTPS
      - "8080:80" # HTTP for testing
    volumes:
      - ./certs:/etc/ssl/certs # Mount certificates
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./certs/selfsigned.key:/etc/ssl/certs/selfsigned.key:ro
    depends_on:
      - db
      - frontend
      - backend

  backend:
    build:
      context: ./studybuddy
      dockerfile: Dockerfile
    container_name: studybuddy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./studybuddy:/app
    env_file:
      - ./studybuddy/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studybuddy-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./certs/selfsigned.key:/etc/ssl/certs/selfsigned.key:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:13
    container_name: studybuddy-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studybuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
