services:

  backend:
    build:
      context: ./studybuddy
      dockerfile: Dockerfile
    container_name: studybuddy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./studybuddy:/app
    env_file:
      - ./studybuddy/.env
    depends_on:
      - db
    networks:
      - studybuddy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studybuddy-frontend
    expose:
      - "80"  # Expose the port internally for Nginx to access
    volumes:
      - ./frontend:/app
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./certs/selfsigned.key:/etc/ssl/certs/selfsigned.key:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - studybuddy-network

  db:
    image: postgres:13
    container_name: studybuddy-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studybuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - studybuddy-network

volumes:
  postgres_data:

networks:
  studybuddy-network:
    driver: bridge