name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to DigitalOcean App Platform
      - name: Deploy to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{  }}
          command: >
            apps create-deployment --app <your-app-id>
